# 47장. 💣 에러 처리

## 📌 47.1 에러 처리의 필요성

에러가 발생하지 않는 코드를 작성하는 것은 불가능하다.

- 직접 발생한 에러에 대처하여 프로그램이 강제 종료되는 것을 방지
- 직접적으로 에러를 발생시키지는 않는 예외 상황에 대한 적절한 대응

### 에러 처리를 구현하는 두 가지 방법

- 예외적인 상황이 발생하면 반환하는 값(null 또는 -1)을 **if문, 단축 평가, 옵셔널 체이닝 연산자**를 통해 처리하는 방법
- 에러 핸들링: 에러 처리 코드를 미리 등록해두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법
    - try … catch … finally

<br>

## 📌 47.2 try … catch … finally문

```jsx
console.log('[Start]');

try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
  foo();
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
  console.error(err); // ReferenceError: foo is not defined
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
  console.log('finally');
}

// try...catch...finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.
console.log('[End]');
```

<br>

## 📌 47.3 Error 객체

`Error` 생성자 함수는 에러 객체를 생성한다.

- 이 Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있음
- 에러 객체는 message, stack 두 개의 프로퍼티를 가짐
    - message : Error 생성자 함수에 인수로 전달한 에러 메시지
    - stack : 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열, 디버깅 목적으로 사용

자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다.

| 생성자 함수 | 인스턴스 설명 |
| -------- | ---------- |
| Error | 일반적 에러 객체 |
| SyntaxError | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체 |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체 |
| TypeError | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체 |
| RangeError | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체 |
| URIError | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError | eval 함수에서 발생하는 에러 객체 |

*보던 놈들이구만..(콘솔에서 많이 봤다..)*

<br>

## 📌 47.4 throw문

에러 객체 생성과 에러 발생은 다른 개념이다.

- Error 생성자 함수로 에러 객체를 생성한다고 해서 에러가 발생하는 것은 아님
- 에러를 ‘발생’시키려면 try 코드 블록에서 throw문으로 에러 객체를 던져야 함
    
    ```jsx
    try {
      // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
      throw new Error('something wrong');
    } catch (error) {
      console.log(error);
    }
    ```
    
<br>

## 📌 47.5 에러의 전파

45장. 프로미스의 [45.1.2절 에러 처리의 한계](https://github.com/xoxojw/modern-js-deep-dive/blob/main/chapters/45장_프로미스.md#4512-에러-처리의-한계)에서 살펴본 것처럼 에러는 호출자 방향으로 전파된다.

즉, 콜 스택의 아래 방향(실행 중인 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.

```jsx
const foo = () => {
  throw Error('foo에서 발생한 에러'); // ④
};

const bar = () => {
  foo(); // ③
};

const baz = () => {
  bar(); // ②
};

try {
  baz(); // ①
} catch (err) {
  console.error(err);
}
```

<div align="center">
  <img src="https://github.com/xoxojw/modern-js-deep-dive/assets/124491335/7c6f0c50-91a1-4ee2-a2c1-5dde763d62f6" width="500px" />
</div>

이 때 throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다는 것에 주의해야 한다.

<br>

또 주의해야 할 것은, 비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없다는 것이다.

setTimeout, 프로미스 후속 처리 메서드 콜백 함수는 태스크 큐나 마이크로태스크 큐에 일시 저장되었다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

- 이때 콜 스택에 푸시된 콜백 함수의 실행 컨텍스트는 콜 스택의 가장 하부에 존재하게 됨
    - 따라서 에러를 전파할 호출자가 존재하지 않음

<br>